# Generated by Django 4.1.3 on 2022-11-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
    ]
