# Generated by Django 4.1.3 on 2022-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movies_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
